### ISSUE TITLE
Illustrate with non-limb-darkened star

### ISSUE THREAD

**Issue by vegajustin26** [ben-cassese/squishyplanet#1]
Tried to use OblateSystem.illustrate with a planet with no limb darkening and ran into an error of matplotlib.pyplot not knowing how to fill the contours: `ValueError: Contour levels must be increasing.` 

Didn't realize that I should have also used 'star_fill=False' for it not to throw errors, but maybe 'star_fill = False' should be explicit in the backend of 'OblateSystem.illustrate' function if the limb darkening coefficients are zero? And/or illustrate could show a uniformly-brightened star instead?

**Comment by ben-cassese** [comment]
Thanks for the catch! Added a check for this in #2, it will now display a uniform disk when all of the limb darkening coefficients are set to zero.
