### ISSUE TITLE
unable to visualize reflection/emission of planets with 2D projection

### ISSUE THREAD

**Issue by vegajustin26** [ben-cassese/squishyplanet#21]
Understand why it's not possible to do this now, but the `OblateSystem.illustrate()` function doesn't catch this yet. Happens when `"parameterize_with_projected_ellipse" : True` in `state` and `"emitted" or "reflected" = True` in `OblateSystem.illustrate()`.

### MRE
<pre>
from squishyplanet import OblateSystem
import jax.numpy as jnp

state = {
    "parameterize_with_projected_ellipse" : True,
    "t_peri": 0.0,
    "times": jnp.linspace(0.0, 5, 400),
    "a": 5.0,
    "projected_f": 0.3,
    "projected_effective_r": 0.3,
    "period": 10,
    "i": jnp.pi/2,
    "ld_u_coeffs": jnp.array([0.0, 0.0]),
    "tidally_locked": False,
}

system = OblateSystem(**state)

system.illustrate(
    true_anomalies=jnp.arange(0, 2 * jnp.pi, jnp.pi / 8),
    window_size=5.0,
    emitted=True, figsize=(3, 3))

</pre>

<details>
<summary><b>Error</b></summary>

<pre>
{
	"name": "ValueError",
	"message": "First argument must be a sequence",
	"stack": "---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[26], line 16
      1 state = {
      2     \"parameterize_with_projected_ellipse\" : True,
      3     \"t_peri\": 0.0,
   (...)
     11     \"tidally_locked\": False,
     12 }
     14 system = OblateSystem(**state)
---> 16 system.illustrate(
     17     true_anomalies=jnp.arange(0, 2 * jnp.pi, jnp.pi / 8),
     18     window_size=5.0,
     19     emitted=True, figsize=(3, 3))
     21 plt.title(\"Oblate planet with no obliquity, parameterized\")

File ~/anaconda3/envs/exoplanet/lib/python3.9/site-packages/squishyplanet/oblate_system.py:879, in OblateSystem.illustrate(self, times, true_anomalies, orbit, reflected, emitted, star_fill, window_size, star_centered, nsamples, figsize)
    869         ax.hexbin(
    870             info[\"sample_xs\"][i],
    871             info[\"sample_ys\"][i],
   (...)
    875             mincnt=1,
    876         )
    878     if emitted:
--> 879         ax.hexbin(
    880             info[\"sample_xs\"][i],
    881             info[\"sample_ys\"][i],
    882             info[\"emitted_intensity\"][i],
    883             cmap=\"plasma\",
    884             gridsize=100,
    885             mincnt=1,
    886         )
    888 ax.set(
    889     aspect=\"equal\",
    890     xlim=(im_center_x - window_size / 2, im_center_x + window_size / 2),
    891     ylim=(im_center_y - window_size / 2, im_center_y + window_size / 2),
    892 )
    894 return

File ~/anaconda3/envs/exoplanet/lib/python3.9/site-packages/matplotlib/__init__.py:1414, in _preprocess_data.<locals>.inner(ax, data, *args, **kwargs)
   1411 @functools.wraps(func)
   1412 def inner(ax, *args, data=None, **kwargs):
   1413     if data is None:
-> 1414         return func(ax, *map(sanitize_sequence, args), **kwargs)
   1416     bound = new_sig.bind(ax, *args, **kwargs)
   1417     auto_label = (bound.arguments.get(label_namer)
   1418                   or bound.kwargs.get(label_namer))

File ~/anaconda3/envs/exoplanet/lib/python3.9/site-packages/matplotlib/axes/_axes.py:4636, in Axes.hexbin(self, x, y, C, gridsize, bins, xscale, yscale, extent, cmap, norm, vmin, vmax, alpha, linewidths, edgecolors, reduce_C_function, mincnt, marginals, **kwargs)
   4499 \"\"\"
   4500 Make a 2D hexagonal binning plot of points *x*, *y*.
   4501 
   (...)
   4632 hist2d : 2D histogram rectangular bins
   4633 \"\"\"
   4634 self._process_unit_info([(\"x\", x), (\"y\", y)], kwargs, convert=False)
-> 4636 x, y, C = cbook.delete_masked_points(x, y, C)
   4638 # Set the size of the hexagon grid
   4639 if np.iterable(gridsize):

File ~/anaconda3/envs/exoplanet/lib/python3.9/site-packages/matplotlib/cbook/__init__.py:938, in delete_masked_points(*args)
    936     return ()
    937 if is_scalar_or_string(args[0]):
--> 938     raise ValueError(\"First argument must be a sequence\")
    939 nrecs = len(args[0])
    940 margs = []

ValueError: First argument must be a sequence"
}

</pre>
</details>

**Comment by ben-cassese** [comment]
Thanks for the catch! This has been patched via an assertion that won't let you illustrate emitted/reflected flux from the planet when `parameterize_with_projected_ellipse` is `True`.
